"""Them thuoc tinh user_name cho comment

Revision ID: 2c004be1baac
Revises: 5f8e5694073a
Create Date: 2026-09-07 09:24:14.165886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c004be1baac'
down_revision: Union[str, Sequence[str], None] = '5f8e5694073a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_name', sa.String(), server_default='Anonymous', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_name')
    # ### end Alembic commands ###
