"""update db

Revision ID: 366823700d08
Revises: 7ab17fa707b8
Create Date: 2026-09-09 14:52:24.009014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366823700d08'
down_revision: Union[str, Sequence[str], None] = '7ab17fa707b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_posts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'image_posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_posts', type_='foreignkey')
    op.drop_column('image_posts', 'user_id')
    # ### end Alembic commands ###
