"""add imagekit_file_id

Revision ID: 67ed41c7ba56
Revises: 366823700d08
Create Date: 2026-09-30 14:04:08.285119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ed41c7ba56'
down_revision: Union[str, Sequence[str], None] = '366823700d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_posts', sa.Column('imagekit_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_posts', 'imagekit_file_id')
    # ### end Alembic commands ###
